### ISSUE TITLE
Is there a way to Download all the node cells as Javascript file?

### ISSUE THREAD

**Issue by bigsnarfdude** [ibm-watson-data-lab/nodebook-code-pattern#18]
![Screen Shot 2019-08-07 at 7 37 30 PM](https://user-images.githubusercontent.com/2282364/62669003-240c9180-b94b-11e9-9ff6-9dbfcc222bd1.png)

**Comment by ptitzler** [comment]
Unfortunately not.

**Comment by bigsnarfdude** [comment]
I managed to "Download as" --> TXT and I'm using a python script to rip thru the node sections and extract the code into a JS file. Now I can create Node scripts in notebook and programatically extract the code. Thanks. Closing.
