### ISSUE TITLE
Cannot find Node.js executable

### ISSUE THREAD

**Issue by markstur** [ibm-watson-data-lab/nodebook-code-pattern#4]
I followed the instructions with Watson Studio and get this:
   Pixiedust database opened successfully
     Pixiedust version 1.1.11
   ERROR: Cannot find Node.js executable

There was originally an error on the customization, but it looks like I got past that. I've done plenty of restarts.

Eventually the only thing I could do to get past this is to add a cell with this:
!conda install -c anaconda nodejs

Then after another restart (or two) it worked.

**Comment by ptitzler** [comment]
I've just tried this and am getting a generic error message (`An error occurred while applying your environment customization. Check the error description you see displayed and possibly modify your customization settings...` ). This seems to be an intermittent problem because I was able to start the environment a couple minutes later without making any changes to the configuration. Following up with Watson Studio support.

**Comment by ptitzler** [comment]
@markstur Can you please run `! cat /var/pod/logs/cust*` in a notebook that's associated with the [node.js customized] environment  and add the output to this issue? Thanks!

**Comment by markstur** [comment]
I hope this is the environment you wanted to see.  Output:
/var/pod/logs/customization-20180712_190042.log
Customizations to apply in DSX-Python27:
--------------------------------------------------------------
# Please add conda channels here
channels:
- defaults

# Please add conda packages here
dependencies:
- nodejs

# Please add pip packages here
# To add pip packages, please comment out the next line
#- pip:
--------------------------------------------------------------

+ conda env update -n DSX-Python27 -f /var/pod/custom/conda-env-update.yml
Fetching package metadata ...........
Solving package specifications: .
nodejs-8.11.1- 100% |###############################| Time: 0:00:00  76.87 MB/s
#
# To activate this environment, use:
# > source activate DSX-Python27
#
# To deactivate an active environment, use:
# > source deactivate
#

**Comment by ptitzler** [comment]
It is, but according to the output the customization was successful, which implies that the nodejs binary should be present. Unfortunately I didn't capture the log when I ran into this issue and the log file is overwritten ...

**Comment by ptitzler** [comment]
We are unable to recreate the issue at this time. Will keep this issue open for now in case somebody else is encountering it. We need the output of `! cat /var/pod/logs/cust*` to diagnose why the nodejs environment  installation intermittently fails.

**Comment by markstur** [comment]
I cannot reproduce this.  It works now.  Even though I created a new project and new environment I'm not sure if that means my account is "clean" from my earlier attempts -- but since I can't repro, I'll close this.
