### ISSUE TITLE
Strange error on printing a var (timing?)

### ISSUE THREAD

**Issue by markstur** [ibm-watson-data-lab/nodebook-code-pattern#5]
I got this error:

NameErrorTraceback (most recent call last)
<ipython-input-31-1c1c6f9696f9> in <module>()
      1 # display modified variable and the new variable
----> 2 print('{} {}'.format(a,g))

NameError: name 'g' is not defined

Then I changed it to (a, a) which worked as expected.  I changed it back to (a, g) and now it works fine.  So it seems like there was a delay and I can't use "Run all".

**Comment by markstur** [comment]
Seeing other problems when "Run all".  It looks like async things require running one cell at a time and giving them time to finish.

**Comment by ptitzler** [comment]
Yes, that's a timing issue. Will add a blurb to the notebook, indicating that cells should be run one at a time.

**Comment by ptitzler** [comment]
Added `Note: Run one cell at a time or unexpected results might be observed.` to the top of the notebook, indicating that scheduling cell execution might result in issues.

**Comment by markstur** [comment]
Closed with #8 notebook also in #9 readme
