### ISSUE TITLE
image links in notebook don't work in Watson Studio

### ISSUE THREAD

**Issue by markstur** [ibm-watson-data-lab/nodebook-code-pattern#6]
Get broken images in Watson Studio.  I don't think there was any step that would download these files. Probably should used full URLs to github content.

Configuring the output as line chart, the visualization looks as follows: 
<img src="images/display_sin_cos.png"></img>

PixieDust presents visualisations of DataFrames using Matplotlib, Bokeh, Brunel, d3, Google Maps and, MapBox. No code is required on your part because PixieDust presents simple pull-down menus and a friendly point-and-click interface, allowing you to configure how the data is presented:

<img src="images/pd_chart_types.png"></img>

**Comment by markstur** [comment]
and other images/ references

**Comment by ptitzler** [comment]
The original notebook was developed to run in a local environment and therefore used local file references. I'll update the notebook to href the images in github, to make this work as expected in local and cloud environments.

**Comment by ptitzler** [comment]
Delivered by #8. All images should now be displayed in the notebook.
